### ISSUE TITLE
Permission Suggestion

### ISSUE THREAD

**Issue by amcmanu3** [xXastaspastaXx/Dimensions#1]
Hi, would it be possible to create a permission node per portal that either allows or disallows a person to bring items through?

**Comment by xXastaspastaXx** [comment]
Hello, sorry for the late response, I never received a notification. I could add that feature but it would be added in the DimensionsAddons plugin. You can find DimensionsAddons [here](https://www.spigotmc.org/resources/dimensionsaddons-spice-up-your-portals.83982/). I will probably add it in the next update.

**Comment by xXastaspastaXx** [comment]
Sorry, i didnt quite get what your suggestion is exactly. Do you mean require permission to teleport item entities throught the portal or require permission for a player to keep their inventory when they go through a portal?
