### ISSUE TITLE
Does not build with `mvn compile`

### ISSUE THREAD

**Issue by VolatileDream** [xXastaspastaXx/Dimensions#6]
Attempting to compile Dimensions complains with a bunch of "symbol missing" errors.

It appears not all the dependencies to compile the mod are included in the `pom.xml` file.

Dependencies that are not found include:
 * Spigot/Bukkit
 * ProtocolLib
 * WorldGuard

**Comment by xXastaspastaXx** [comment]
Sorry about that. I used to include the dependencies in my build path since I would provide the jar anyway.
I will not update or change anything since I am currently working on a re-write of Dimensions.
Sorry for the late reply
